version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aiops_db
      POSTGRES_USER: aiops
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run cmd/api/main.go
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run cmd/worker/main.go
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
