version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-ops-assistant-api
    command: /bin/api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db

  summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-ops-assistant-summarizer
    command: /bin/summarizer
    env_file: .env
    depends_on:
      - db

  triage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-ops-assistant-triage
    command: /bin/triage
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: ai-ops-assistant-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db/init-uuid.sql:/docker-entrypoint-initdb.d/init-uuid.sql

volumes:
  postgres-data:
