// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangelogEntry struct {
	Scope   string `json:"scope"`
	Summary string `json:"summary"`
}

type GitCommitInput struct {
	Message string `json:"message"`
	Author  string `json:"author"`
	Date    string `json:"date"`
}

type LogInput struct {
	Text string `json:"text"`
}

type LogSummary struct {
	Summary   string `json:"summary"`
	Category  string `json:"category"`
	Timestamp string `json:"timestamp"`
}

type Query struct {
}

type TicketClassification struct {
	Severity string `json:"severity"`
	Type     string `json:"type"`
	Owner    string `json:"owner"`
}

type TicketInput struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
